### ISSUE TITLE
Determine package interface

### ISSUE THREAD

**Issue by friendlyanon** [microsoft/ifc#29]
The current CMake files do not support reuse by clients due to the missing install rules and missing CMake package. I would like to know what would be the way for people to consume this SDK.

Being careful not to cause potential name conflicts with packages dealing with CAD applications' Industry Foundation Classes (.ifc), I think this would be one way for a consumer to use this SDK:

```cmake
# the package name is MicrosoftIFC, found in e.g. <prefix>/lib/cmake/MicrosoftIFC
find_package(MicrosoftIFC REQUIRED)

# the SDK target is an interface target that link both ifc-dom and ifc-reader, as a convenient all in one target
target_link_libraries(AwesomeIFCConsumer PRIVATE MicrosoftIFC::SDK)
```

I would like to work on this once the requirements are known.

**Comment by GabrielDosReis** [comment]
I believe the package `MicrosoftIFC`, and target name `MicrosoftIFC::SDK` sound great!

**Comment by friendlyanon** [comment]
Should the printer also be installed? If yes, should it also be made available via the CMake package (e.g. via a `IFC_PRINTER_EXECUTABLE` variable)? I have not yet looked at its output, so I don't know if it's useful for scripting.

**Comment by GabrielDosReis** [comment]
> Should the printer also be installed? If yes, should it also be made available via the CMake package (e.g. via a `IFC_PRINTER_EXECUTABLE` variable)? I have not yet looked at its output, so I don't know if it's useful for scripting.

The direction we are envisioning for command-line utilities is to have subcommands of `ifc.exe` a la GIT.  So, for now don't make the printer available via CMake package yet.  In fact, don't install the printer yet.

**Comment by friendlyanon** [comment]
Oh my goodness. There goes me trying to figure out signing commits.

**Comment by GabrielDosReis** [comment]
@friendlyanon  - it looks like merging your PR makes CodeQL automatic run fails.  They claim they can no longer auto build with the following command:

```
cmake -DCMAKE_VERBOSE_MAKEFILE=ON -DBUILD_DOCS=OFF -DCATKIN_ENABLE_TESTING=OFF -DBUILD_DOCUMENTATION=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS=  -DCMAKE_C_FLAGS=
```

Any idea what additional command line argument to CMake would have been necessary?

**Comment by friendlyanon** [comment]
Either by using vcpkg or passing `CMAKE_MODULE_PATH` as suggested in the PR.

**Comment by GabrielDosReis** [comment]
> Either by using vcpkg or passing `CMAKE_MODULE_PATH` as suggested in the PR.

Yeah, but that workflow is automatically run based on build system definition.  The CI for release build is successful without needing anything additional.  Could you have a look at the CodeQL workflow?

**Comment by friendlyanon** [comment]
Based on the [documentation](https://docs.github.com/en/code-security/code-scanning/creating-an-advanced-setup-for-code-scanning/codeql-code-scanning-for-compiled-languages#autobuild-for-cc), a `build.bat` and `build.sh` script needs to be added ot the root of the project.

**Comment by GabrielDosReis** [comment]
> Based on the [documentation](https://docs.github.com/en/code-security/code-scanning/creating-an-advanced-setup-for-code-scanning/codeql-code-scanning-for-compiled-languages#autobuild-for-cc), a `build.bat` and `build.sh` script needs to be added ot the root of the project.

Thanks.  I converted the implicit CodeQL build into an explicit workflow in the proposed PR #41 .  Please, could you rebase your proposed fix on that PR?  You can push (not force push) to that branch.  Thanks!
