### ISSUE TITLE
How to build on Linux?

### ISSUE THREAD

**Issue by whoan** [microsoft/ifc#44]
Doc states "_the code has been tested to work on Windows and Linux_". I guess the Linux part means in Windows under WSL, correct?

A quick attempt to build on Linux (no WSL) is giving me this error:

    CMake Error at CMakeLists.txt:19 (find_package):
      By not providing "FindMicrosoft.GSL.cmake" in CMAKE_MODULE_PATH this
      project has asked CMake to find a package configuration file provided by
      "Microsoft.GSL", but CMake did not find one.

      Could not find a package configuration file provided by "Microsoft.GSL"
      with any of the following names:

        Microsoft.GSLConfig.cmake
        microsoft.gsl-config.cmake

      Add the installation prefix of "Microsoft.GSL" to CMAKE_PREFIX_PATH or set
      "Microsoft.GSL_DIR" to a directory containing one of the above files.  If
      "Microsoft.GSL" provides a separate development package or SDK, be sure it
      has been installed.

    -- Configuring incomplete, errors occurred!

**Comment by GabrielDosReis** [comment]
@friendlyanon  - a fallout from the packaging support.  I know we discussed this in the PR #34 , but if you could shime in here.

> I guess the Linux part means in Windows under WSL, correct?

No.  It means stock linux; including the CI runner ubuntu on GitHub, see the [CI workflow](https://github.com/microsoft/ifc/blob/main/.github/workflows/cmake.yml) which runs also on linux (ubuntu-latest).

The simplest is to have [GSL](https://github.com/microsoft/GSL) installed on your system with your favorite package manager, or use vckpg to build both GSL and this repo.

**Comment by friendlyanon** [comment]
The Microsoft GSL library is available from many repositories:

https://repology.org/project/c++-gsl/versions  
https://repology.org/project/cppgsl/versions  
https://repology.org/project/libmicrosoft-gsl/versions  
https://repology.org/project/msgsl/versions  
https://repology.org/project/ms-gsl/versions

You may provide the GSL dependency in the way you prefer. CI for example uses vcpkg and contributors are encouraged to do the same in [HACKING.md](https://github.com/microsoft/ifc/blob/main/HACKING.md).

If all these options weren't enough already, you may also rely on FetchContent via [FindMicrosoft.GSL.cmake](https://github.com/microsoft/ifc/blob/main/cmake/find/FindMicrosoft.GSL.cmake).

If all else fails, you may also just do it all manually.

**Comment by whoan** [comment]
Thanks both @GabrielDosReis and @friendlyanon for your help. I will give it a try soon and will let you know. Closing this one.

**Comment by GabrielDosReis** [comment]
Please, do let us now how it goes and what else can be done to smooth the onboarding process with respect to build.  Because we would like to avoid 

> If all else fails, you may also just do it all manually.

for newcomers or people checking out the project for the first time.

**Comment by friendlyanon** [comment]
There is a reason why I listed that as the last option. Building the project is one thing. Reusing it is another.

On that note, I think it should also be discussed what the project should look like when consumed via a package manager like vcpkg. I'll make a new issue for that.

**Comment by whoan** [comment]
@GabrielDosReis @friendlyanon I am under Arch Linux so after a simple `pacman -S microsoft-gsl` the compilation worked.

Still would like to find a way to give this a try in an even easier way. If I find such a way (eg: through Docker), I can let you know.

Thanks

**Comment by GabrielDosReis** [comment]
> I am under Arch Linux so after a simple `pacman -S microsoft-gsl` the compilation worked.

Thanks for the update.
It is indeed an issue that the lack of a common name for GSL package across linux distros can create lot of confusion.  For example, on Ubuntu GSL is available as `libmsgsl-dev`.

> Still would like to find a way to give this a try in an even easier way.

What do you need to get there?

**Comment by whoan** [comment]
> What do you need to get there?

From my end: time. I already played a little but still don't know how to try the SDK. This is what I got so far: https://github.com/whoan/ifc-playground

From your end: Some clarification please:

1.  From readme: _There are a couple of IFC files checked into the repo for basic testing purposes._ -> **I can't find those**
2. From readme: _Longer term, we want to be able to generate IFC files using the SDK itself._ -> **Any ETA?** I don't have a MS compiler at hand to generate IFC files

Thanks!
