### ISSUE TITLE
Packaging (vcpkg, etc)

### ISSUE THREAD

**Issue by friendlyanon** [microsoft/ifc#45]
Once there is a 0.43.1 tag, I think it'd be time to prepare a vcpkg port for the project for easy consumption.

Since the package name for the CMake package followed the GSL pattern, should this project also be packaged as `ms-ifc`? Maybe even `ms-ifc-sdk`?

**Comment by GabrielDosReis** [comment]
I suspect we would think along two packages:  (1) binaries and libraries; (2) header files + (1).

If one were to package this in the linux world, one would [likely have something `ms-ifc` for (1) and `ms-ifc-dev` for (2).

We do plan on having an executable `ifc` or `ifc.exe` that acts on IFC files, with subcommands a la GIT.  For example, you would have an executable/load unit `ifc-print.dll` or `ifc-print.so` that would be used to implement `ifc print`.  Once built and installed, these binaries do not need the header files for development.

**Comment by friendlyanon** [comment]
Based on how GSL is packaged already (https://github.com/microsoft/ifc/issues/44#issuecomment-1755976453) it seems Linux package managers have their own conventions for naming, so I don't know how much control projects have there. In that sense, this project only has content for a `-dev` package right now.

I was thinking mainly about Conan and vcpkg, where it's easier to create a package.

**Comment by GabrielDosReis** [comment]
> this project only has content for a `-dev` package right now

Almost.  The contents of `samples` are not `-dev` package in the conventional sense; they are part of the whole IFC SDK experience.  I do agree though that we can't tell linux distros how they should name packages they distribute.  I am think more in terms of differentiated experience:
   1. Someone who just wants to use the IFC tool to semantically explore a header file or a module interface -- see what is in `samples` for example.  They don't care about header files and all that.
   2.  Someone, like you and me, who wants to build cool stuff on top of the reader and dom components through the header file interfaces.

Maybe we just release one thing, and leave it to packagers how to separate those things, but then we would be back to the naming problem that you are rightfully highlighting.   That has the property of being simple - and simplicity is always a premium to cherish. 

> I was thinking mainly about Conan and vcpkg, where it's easier to create a package.

Thanks for clarifying that.

From that perspective, let's go with `ms-ifc-sdk` for the whole thing.

**Comment by friendlyanon** [comment]
> From that perspective, let's go with `ms-ifc-sdk` for the whole thing.

Excellent! I would like to create such a port for vcpkg once 0.43.1 is tagged.

**Comment by GabrielDosReis** [comment]
Is this still an active issue, or it was resolved by the merge of the port https://github.com/microsoft/vcpkg/pull/35972

**Comment by friendlyanon** [comment]
It was resolved. I just forgot about closing this issue.
